// examples/angular-todo-generated/src/app/app.component.ts
import { Component } from '@angular/core';
import { TodoFacade } from './store/facade';

/**
 * Root App Component
 */
@Component({
    selector: 'app-root',
    template: `
    <div class="app">
      <header class="app-header">
        <h1>📝 Todo App</h1>
        <p class="subtitle">
          Built with Polystate Generated NgRx + Angular
        </p>
      </header>

      <main class="app-main">
        <!-- Add Todo Form -->
        <form (ngSubmit)="onAddTodo()" class="add-todo-form">
          <input
            type="text"
            [(ngModel)]="newTitle"
            name="title"
            placeholder="Add a new todo..."
            class="todo-input"
          />
          <button type="submit" class="add-button">Add Todo</button>
        </form>

        <!-- Filter Buttons -->
        <div class="filter-buttons">
          <button
            *ngFor="let f of filters"
            [class.active]="(filter$ | async) === f"
            (click)="onSetFilter(f)"
            class="filter-button"
          >
            {{ f | titlecase }}
          </button>
        </div>

        <!-- Todo List -->
        <div class="todo-list">
          <p *ngIf="(filteredTodos$ | async)?.length === 0" class="empty-message">
            {{ (filter$ | async) === 'all'
              ? 'No todos yet. Add one to get started!'
              : 'No ' + (filter$ | async) + ' todos.' }}
          </p>
          <div
            *ngFor="let todo of filteredTodos$ | async"
            class="todo-item"
          >
            <input
              type="checkbox"
              [checked]="todo.done"
              (change)="onToggleTodo(todo.id)"
              class="todo-checkbox"
            />
            <span [class.done]="todo.done" class="todo-title">
              {{ todo.title }}
            </span>
            <button
              (click)="onRemoveTodo(todo.id)"
              class="remove-button"
              aria-label="Remove todo"
            >
              ×
            </button>
          </div>
        </div>

        <!-- Stats -->
        <div
          *ngIf="(filteredTodos$ | async)?.length && (filteredTodos$ | async)?.length > 0"
          class="stats"
        >
          <span>{{ activeTodoCount$ | async }} active</span>
          <span>·</span>
          <span>{{ completedTodoCount$ | async }} completed</span>
        </div>
      </main>
    </div>
  `,
    styleUrls: ['./app.component.css'],
    standalone: false,
})
export class AppComponent {
    newTitle = '';
    filters: Array<'all' | 'active' | 'completed'> = [
        'all',
        'active',
        'completed',
    ];

    filteredTodos$ = this.todoFacade.filteredTodos$;
    filter$ = this.todoFacade.filter$;
    activeTodoCount$ = this.todoFacade.activeTodoCount$;
    completedTodoCount$ = this.todoFacade.completedTodoCount$;

    constructor(public todoFacade: TodoFacade) { }

    onAddTodo(): void {
        if (this.newTitle.trim()) {
            this.todoFacade.addTodo(this.newTitle);
            this.newTitle = '';
        }
    }

    onToggleTodo(id: number): void {
        this.todoFacade.toggleTodo(id);
    }

    onRemoveTodo(id: number): void {
        this.todoFacade.removeTodo(id);
    }

    onSetFilter(filter: 'all' | 'active' | 'completed'): void {
        this.todoFacade.setFilter(filter);
    }
}

// examples/react-todo-generated/src/App.tsx
import React, { useState } from 'react';
import './App.css';
import {
    useActiveTodoCount,
    useFilter,
    useFilteredTodos,
    useTodoDispatch,
} from './store/hooks';

/**
 * Todo Application
 * Demonstrates Polystate code generation for React + Redux
 */
export function App() {
  const [title, setTitle] = useState('');
  const todos = useFilteredTodos();
  const filter = useFilter();
  const activeCount = useActiveTodoCount();
  const { addTodo, toggleTodo, removeTodo, setFilter } = useTodoDispatch();

  const handleAddTodo = (e: React.FormEvent) => {
    e.preventDefault();
    if (title.trim()) {
      addTodo(title);
      setTitle('');
    }
  };

  return (
    <div className="app">
      <header className="app-header">
        <h1>📝 Todo App</h1>
        <p className="subtitle">
          Built with Polystate Generated Redux + React
        </p>
      </header>

      <main className="app-main">
        {/* Add Todo Form */}
        <form onSubmit={handleAddTodo} className="add-todo-form">
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Add a new todo..."
            className="todo-input"
          />
          <button type="submit" className="add-button">
            Add Todo
          </button>
        </form>

        {/* Filter Buttons */}
        <div className="filter-buttons">
          {(['all', 'active', 'completed'] as const).map((f) => (
            <button
              key={f}
              className={`filter-button ${filter === f ? 'active' : ''}`}
              onClick={() => setFilter(f)}
            >
              {f.charAt(0).toUpperCase() + f.slice(1)}
            </button>
          ))}
        </div>

        {/* Todo List */}
        <div className="todo-list">
          {todos.length === 0 ? (
            <p className="empty-message">
              {filter === 'all'
                ? 'No todos yet. Add one to get started!'
                : `No ${filter} todos.`}
            </p>
          ) : (
            todos.map((todo) => (
              <div key={todo.id} className="todo-item">
                <input
                  type="checkbox"
                  checked={todo.done}
                  onChange={() => toggleTodo(todo.id)}
                  className="todo-checkbox"
                />
                <span className={`todo-title ${todo.done ? 'done' : ''}`}>
                  {todo.title}
                </span>
                <button
                  onClick={() => removeTodo(todo.id)}
                  className="remove-button"
                  aria-label="Remove todo"
                >
                  ×
                </button>
              </div>
            ))
          )}
        </div>

        {/* Stats */}
        {todos.length > 0 && (
          <div className="stats">
            <span>{activeCount} active</span>
            <span>·</span>
            <span>{todos.length - activeCount} completed</span>
          </div>
        )}
      </main>
    </div>
  );
}

export default App;
